# Generated by Django 5.0.6 on 2024-07-17 16:51

import django.core.validators
import shopowners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Owner_Registartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('shop_name', models.CharField(max_length=1000)),
                ('mail_id', models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.'), django.core.validators.RegexValidator(code='invalid_email', message='Enter a valid email address.', regex='^[\\w.%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$')])),
                ('phone_number', models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be at least 10 digits.'), django.core.validators.MaxLengthValidator(10, message='Phone number cannot be more than 10 digits.')], verbose_name='Phone Number')),
                ('street_address', models.CharField(max_length=500)),
                ('village', models.CharField(max_length=500)),
                ('mandal', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('zip_pin_code', models.IntegerField()),
                ('password', models.CharField(max_length=100, validators=[shopowners.models.validate_password_strength])),
            ],
        ),
    ]
