# Generated by Django 5.0.6 on 2024-07-17 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_owner_registartion',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be at least 10 digits.'), django.core.validators.MaxLengthValidator(10, message='Phone number cannot be more than 10 digits.')], verbose_name='Phone Number'),
        ),
    ]
